#!/usr/bin/env bash
# Build a single SQL script for in-memory DuckDB / Metabase Init SQL.
# Output is generated — do not edit by hand. Re-run after changing cnshift.sql.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${1:-$ROOT/sql/init-memory.sql}"
{
	cat <<'EOF'
-- Generated by sql/build-init-memory.sh — do not edit.
-- In-memory DuckDB / Metabase Init SQL / JDBC session_init_sql_file.
-- .read is CLI-only; this file inlines INSTALL + LOAD + sql/cnshift.sql.
INSTALL spatial;
LOAD spatial;

EOF
	cat "$ROOT/sql/cnshift.sql"
} > "$OUT"
echo "wrote $OUT"
